modLoader="javafml" #mandatory
loaderVersion="[39,]" #mandatory
license="MIT" #mandatory
credits="LK1905" #optional
[[mods]] #mandatory
modId="simpleclimate" #mandatory
version="0.1" #mandatory
displayName="SimpleClimate" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/SimpleClimateMod" #optional
description='''
A mod that creates more accurate climate bands in Minecraft. 
'''